# Generated by Django 4.0.2 on 2023-01-22 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_users_customerusers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerusers',
            options={'verbose_name_plural': 'CustomUser'},
        ),
    ]
