# Generated by Django 4.0.2 on 2022-10-08 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featuredproducts',
            options={'verbose_name': 'Featured Product'},
        ),
    ]
