# Generated by Django 4.0.2 on 2022-10-08 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_featuredproducts_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuredproducts',
            name='image',
        ),
    ]
