# Generated by Django 4.0.2 on 2022-12-30 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'Contact'},
        ),
    ]
