# Generated by Django 4.0.2 on 2023-01-20 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_featuredproducts_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredproducts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=1),
        ),
    ]
