# Generated by Django 4.0.2 on 2023-01-27 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_category_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
